<?php

/**
 * @file
 * Module file for the tao_iching module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block_content\BlockContentInterface;

/**
 * Implements HOOK_theme().
 *
 * @param array $existing
 *   The existing theme implementations.
 * @param string $type
 *   The type of the theme hook (e.g. 'theme', 'block', 'region').
 * @param string $theme
 *   The name of the theme being rendered.
 * @param string $path
 *   The path to the module or theme implementing the hook.
 *
 * @return array
 *   An array of theme hook definitions.
 */
function tao_iching_theme($existing, $type, $theme, $path) {
  $variables = [
    'form__tao_iching_form' => [
      'render element' => 'children',
      'template' => 'form--tao-iching-form',
    ],
    'block__i_ching_block' => [
      'variables' => [
        'iching' => NULL,
      ],
      'template' => 'block--i-ching-block',
    ],
  ];
  return $variables;
}

/**
 * Implements HOOK_cron().
 */
function tao_iching_cron() {
  /* remove readings whose storage life is expired */
  $iChing = \Drupal::service('tao_iching.service');
  $database = \Drupal::database();
  $idArray = $database->select('tao_iching_readings', 'n')
    ->fields('n', ['id', 'timestamp'])
    ->execute()
    ->fetchAll();
  foreach ($idArray as $value) {
    if ($iChing->checkTimestamp($value->timestamp)) {
      $iChing->deleteReading($value->id);
    }
  }
  /* clean any broken readings from database */
  $iChing->cleanIchingDb();
}

/**
 * Implements HOOK_form_alter().
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 * @param [type] $form_id
 *   The form ID.
 */
function tao_iching_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'tao_iching_form') {
    $form['#attached']['library'][] = 'tao_iching/tao_iching.library';
    $form['#theme'] = 'form__tao_iching_form';
  }
  if ($form_id == 'tao_iching_settings_form') {
    $form['#attached']['library'][] = 'tao_iching/tao_iching.library';
  }
}

/**
 * The tao_iching_create_reading function.
 *
 * @return string
 *   Returns an id string.
 */
function tao_iching_create_reading() {
  $user = \Drupal::currentUser();
  $iChing = \Drupal::service('tao_iching.service');
  $id = $iChing->makeId();
  $sessionId = $id['id'];
  $question = "A general reading please.";
  $iChing->readingInit($id, $user->getDisplayName(), $question);
  $i = 1;
  while ($i < 7) {
    /* generate hexagram line */
    $user_click = $iChing->line();
    foreach ($user_click as $key => $value) {
      if ($key != "line" && $key != "coinsval") {
        $keyBucket = $key;
        $valBucket = $value;
      }
    }
    $line = $user_click['line'];
    $tri_name = $keyBucket;
    $code = $valBucket;
    $coinsval = $user_click['coinsval'];

    $iChing->insertLine($sessionId, $i, $line, $tri_name, $code, $coinsval);
    $i++;
  }
  sleep(2);
  return $id['id'];
}

/**
 * The tao_iching_create_finished function.
 *
 * @param string $success
 *   Whether the reading creation process was successful.
 * @param array $results
 *   The results of the reading creation process.
 * @param array $operations
 *   The operations involved in the reading creation process.
 */
function tao_iching_create_finished($success, $results, $operations) {
  if ($success) {
    $message = t('Reading creation completed successfully.');
  }
  else {
    $message = t('Finished with an error.');
  }
  \Drupal::messenger()->addStatus($message);
}

/**
 * Implements hook_theme_suggestons_alter()
 *
 * @param array $suggestions
 *   The array of theme suggestions to alter.
 * @param array $variables
 *   The variables available for the theme suggestions.
 * @param string $hook
 *   The theme hook.
 */
function tao_iching_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'form' & !empty($variables['element']['#theme'])) {
    $suggestions[] = 'form__' . $variables['element']['#theme'][0];
  }
  if ($hook == 'region' & !empty($variables['element']['#theme'])) {
    $suggestions[] = 'region__' . $variables['element']['#theme'][0];
  }

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }

}

/**
 * Implements hook_theme_suggestons_block_alter()
 *
 * @param array $suggestions
 *   The array of theme suggestions to alter.
 * @param array $variables
 *   The variables available for the theme suggestions.
 */
function tao_iching_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }

}
